Ys1000 int
jibudata/amberapp pull request #14
Opened 2022-01-11 14:24 UTC by jerry-jibu

2022-01-11 14:39 UTC, half-life666 approved these changes

2022-01-13 09:54 UTC, big-appled requested changes

2022-01-13 09:54 UTC, big-appled commented on Makefile
> +VERSION ?= $(shell git rev-parse --abbrev-ref HEAD).$(shell git rev-parse --short HEAD)
why change to such format?  main.76d2fbd

2022-01-13 09:54 UTC, big-appled commented on config/default/kustomization.yaml
> +namespace: qiming-backend
```suggestion
namespace: amberapp-system
```

2022-01-13 09:54 UTC, big-appled commented on config/manager/kustomization.yaml
> +namespace: qiming-backend
```suggestion
  newTag: 0.0.3
```

2022-01-14 03:42 UTC, big-appled approved these changes

2022-01-14 10:27 UTC, merged